# GIFs created using VHS (https://github.com/charmbracelet/vhs)

Output long_haiku.gif

Set FontSize 20
Set Width 1200
Set Height 600

Type "python3 claiku"
Sleep 1
Enter
Sleep 1
Type "a CLI haiku assistant"
Sleep 2
Backspace 9
Type "tool"
Enter
Type "to count all of the syllables"
Sleep 2
Enter
Type "in your three-line poem"
Sleep 2
Up
Right 6
Sleep 1
Backspace 21
Type " syllables per line"
Sleep 1
Down
Enter

Sleep 5
Enter
